### ISSUE TITLE
Should "Compatible Version" mention 0-RTT?

### ISSUE THREAD

**Issue by RyanTheOptimist** [ekr/draft-schinazi-quic-version-negotiation#2]
Consider the case of two difference QUIC versions which are roughly identical in terms of the crypto/handshake/packet layer. But imagine that these two versions, say, renumber streams or some other change which makes 0-RTT data look different. I would assume that such versions would not be "compatible" for the purposes of section 7? 

Or alternatively, they could be considered compatible, but the server MUST not process 0-RTT packets, and the client must "unwind" the 0-RTT state (un-open streams, etc)?

**Comment by DavidSchinazi** [comment]
I agree, we should add text to discuss this, perhaps in a section of recommendations for writers of new versions. When deciding whether two versions are compatible, the cost of rewriting 0-RTT data from one version to the next should be taken into account.

**Comment by grmocg** [comment]
Interested in seeing where this goes.

**Comment by DavidSchinazi** [comment]
Closing this issue, follow along on the [new repository](https://github.com/quicwg/version-negotiation/issues/6).
