### ISSUE TITLE
The client is unable to detect downgrade attacks

### ISSUE THREAD

**Issue by RyanTheOptimist** [ekr/draft-schinazi-quic-version-negotiation#3]
While I recognize that it is an explicit design choice of this extension to move all the downgrade detection to the server, it seems unfortunate to prevent the client from detecting the downgrade and instead relying on the server to do so. (I could imagine that some server implementations are lazy/broken and might not perform this detection)?

Alternatively, if the server delivered to the client a set of lists of versions that the server (or the server's peers) might have sent in VN packets, then the client could compare the actual VN packet it received with the elements in the set and detect the case where none of them match.  Commonly the server would send one such list, but if it were participating in a staggered rollout, it could send both the "old" and "new" lists?

**Comment by DavidSchinazi** [comment]
Closing this issue, follow along on the [new repository](https://github.com/quicwg/version-negotiation/issues/5).
